# Generated by Django 4.2.7 on 2025-04-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_analyzer', '0003_product_brand_product_category_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
