# Generated by Django 4.2.7 on 2025-04-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_analyzer', '0004_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
